[build]
  command = "./setup.sh"
  publish = "public"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  baseUrl = "https://polarhive.net"
  prettyURLs = true

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

 [plugins.inputs]
 baseUrl = "https://polarhive.net"
 sitemapPath = "/sitemap.xml"
 ignorePeriod = 0
 providers = ["google", "yandex"]

[[redirects]]
  from = "https://polarhive.netlify.app/*"
  to = "https://polarhive.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://main--polarhive.netlify.app/*"
  to = "https://polarhive.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/afk"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/crypto"
  to = "/donate"
  status = 301
  force = true

[[redirects]]
  from = "/apple"
  to = "/blog/apple"
  status = 301
  force = true

[[redirects]]
  from = "/brave"
  to = "/blog/brave"
  status = 301
  force = true

[[redirects]]
  from = "/firefox"
  to = "/blog/firefox"
  status = 301
  force = true

[[redirects]]
  from = "/browsers"
  to = "/blog/firefox"
  status = 301
  force = true

[[redirects]]
  from = "/blogroll"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/arceo"
  to = "https://github.com/polarhive/arceo"
  status = 301
  force = true

[[redirects]]
  from = "/jukebox"
  to = "https://github.com/polarhive/jukebox"
  status = 301
  force = true

[[redirects]]
  from = "/knowledge"
  to = "/wiki"
  status = 301
  force = true

[[redirects]]
  from = "/garden"
  to = "/wiki"
  status = 301
  force = true

[[redirects]]
  from = "/git"
  to = "/codeberg"
  status = 301
  force = true

[[redirects]]
  from = "/codeberg"
  to = "https://codeberg.org/polarhive"
  status = 301
  force = true

[[redirects]]
  from = "/feed"
  to = "/blog/index.xml"
  status = 301
  force = true

[[redirects]]
  from = "/rss"
  to = "/blog/index.xml"
  status = 301
  force = true

[[redirects]]
  from = "/posts/*"
  to = "/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/bucket"
  to = "/.well-known/bucketlist.txt"
  status = 301
  force = true

[[redirects]]
  from = "/bucket.txt"
  to = "/.well-known/bucketlist.txt"
  status = 301
  force = true

[[redirects]]
  from = "/bucketlist"
  to = "/.well-known/bucketlist.txt"
  status = 301
  force = true

[[redirects]]
  from = "/bucketlist.txt"
  to = "/.well-known/bucketlist.txt"
  status = 301
  force = true

[[redirects]]
  from = "/blog/dishonest-trebleshot-clones-in-the-name-of-madeinindia/*"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/blog/2019/04/18/deletefacebook/*"
  to = "/blog/breaking-up-with-facebook"
  status = 301
  force = true

[[redirects]]
  from = "/security.txt"
  to = "/.well-known/security.txt"
  status = 301
  force = true

[[redirects]]
  from = "/pgp"
  to = "/.well-known/polarhive_gpg.txt"
  status = 301
  force = true

[[redirects]]
  from = "/gpg"
  to = "/.well-known/polarhive_gpg.txt"
  status = 301
  force = true

[[redirects]]
  from = "/assets/polarhive_gpg.txt"
  to = "https://polarhive.net/.well-known/polarhive_gpg.txt"
  status = 301
  force = true

[[redirects]]
  from = "/meta"
  to = "/.well-known/meta.txt"
  status = 301
  force = true

[[redirects]]
  from = "/gb"
  to = "/guestbook"
  status = 301
  force = true

[[redirects]]
  from = "https://blog.polarhive.net/*"
  to = "https://polarhive.net/blog"
  status = 301
  force = true

[[redirects]]
  from = "https://git.polarhive.net/*"
  to = "/git"
  status = 301
  force = true

[[redirects]]
  from = "/arch.sh"
  to = "https://github.com/polarhive/dots/raw/branch/main/install.sh"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
